### ISSUE TITLE
Using variable only for specific executable

### ISSUE THREAD

**Issue by Abergard** [NadzwyczajnaGrupaRobocza/papuc_exercises#14]
It would be nice to have functionality to add flag only for specific executable

**Comment by lukasz-m-maciejewski** [comment]
Use 
target_compile_options(<target-name> PRIVATE <any-string>)

This will instert the content of <any-string> into the compilation command for <target-name>, tight after CMAKE_CXX_FLAGS content, eg:
target_compile_options(lm-calculator-lib PRIVATE "-Weffc++")

https://cmake.org/cmake/help/v3.0/command/target_compile_options.html
