### ISSUE TITLE
Continuous Integration for Windows Build

### ISSUE THREAD

**Issue by lukasz-m-maciejewski** [NadzwyczajnaGrupaRobocza/papuc_exercises#19]
If possible, investigate setting up CI for Windows builds https://www.appveyor.com/

**Comment by Abergard** [comment]
Done. The file configuration appveyor has been added and works with our project file.

**Comment by lukasz-m-maciejewski** [comment]
:100: :+1: :open_mouth: :cake: :ice_cream: :octocat: :racehorse: :tada: :champagne:
